### PR TITLE
hashids scala-way

### PR DESCRIPTION
**Pull request by ancane**
Hi, newhoggy!

I'v been using Java version of hashids for some time in my scala project and when I found your scala port, I was eager to switch and use native library. But then I found that code didn't differ from java version... All those vars ... So I went with a rewrite, to make it more into scala-way.
Also I found and fixed couple things:
1. Decode function result check with encode function. Returing empty result in case of buggy decode function isn't good idea. Decode should be working fine without double checks.
2. Implicit functions in separate file. Those naturally fit into complanion object next to apply functions.
3. Trying to fix incorrect alphabet in constructor: if it's incorrect, it should be clearly communicated back to programmer. Otherwise alphabet is different from what library client thinks.

Hope this is helpfull.

PS. One other thing i dislike is that your repo is a fork of java's one. Scala deserves it's own repo, I think. It's not possible to pull updates and publish pull requests to java repo anyway.

### CODE REVIEW

**Comment by newhoggy** [comment]
Hi, Ancane,

I've been meaning to get around to removing some of the vars, but didn't get around to it.  I had concentrated on removing all those mutable fields and left the vars in because it was localised and not so bad.  It is really awesome that you've gone and removed many of them.

The other thing I was worried about with changing to use functional version of the Fisher-Yates random shuffle algorithm was due to it having the algorithmic complexity of O(n*log n).  The optimal imperative version of the algorithm is O(n): http://www.haskell.org/haskellwiki/Random_shuffle

It's possible the data size we are dealing with, that the algorithmic complexity doesn't matter - but I haven't yet measured it.

Your point about the "decode" function, I had also originally taken it out, but added it back in at the request of Ivan, the Hashids maintainer.  It is there to prevent a decode in the case where the wrong salt was supplied and was intentionally added to flag that error.  I didn't like the fact that it returns an empty list though because the empty list is a valid value to encode.

I'm not too fussed with where to put the implicits.  I had modelled it on the Scalaz way of putting the implicits in separate syntax file.

I also agree with your final point, though there needs to be an easy way for someone who is using a different Hashids to move to Scala from another language and vice-versa.  Perhaps there should be a version of Hashids.apply that fixes it up and a version that doesn't.

It might also be worthwhile sharing these ideas with the Hashids maintainer to try and get some of the sensible behaviours standardised across all the languages.

Cheers,

-John

**Comment by ancane** [comment]
Thanks, Newhoggy. I'd still like to clarify couple things.

> About functional version of random shuffle

I didn't change the complexity of original version. What I did is replaced imperative code with tail-optimized recursion, which means it has same complexity as imperative loops. `@talirec` annotation ensures that.

> About decode function

I'v checked couple implementions of Hashids and I didn't find anything related to "wrong salt". Java port doesn't have that double check either. Could you, please, describe the issue more so we could, maybe, write some tests for such cases?

**Comment by newhoggy** [comment]
Hi Ancane,

Regarding, code complexity: Cool.  I'll have a look tomorrow.

Regarding decode function: This is the message I got from Ivan: "Regarding the encode inside the decode: after decoding an id, it’s possible to get a random set of numbers if the user provided wrong salt value. So, a quick encode is done with those integers to be sure the right salt value was provided"

**Comment by ancane** [comment]
Thank you, John.
I think I got what "wrong salt" means.
When client tries to decode a hash, that was produced with salt, different from salt currect Hashids object has, then integer value will be erroneous. Double check is beneficial in this case. But still, I'd throw a clear exception instead of empty list.
I'll have to make some changes to my pull request.
Thx.

**Comment by ilanbiala** [comment]
@ancane @newhoggy is this going to be merged in or should it be closed?

**Comment by newhoggy** [comment]
Merged.  But bear with me a moment while I upgrade dependencies and the build and perform some general cleanup before publishing.

**Comment by ilanbiala** [comment]
Great, thanks.

**Comment by newhoggy** [comment]
Latest code has been published.  Note that, the code is now being published to a different repository.

**Pull request merged**
